### ISSUE TITLE
能给份java版的吗

### ISSUE THREAD

**Issue by DyncKathline** [javakam/FileOperator#1]

**Comment by javakam** [comment]
建议直接上 Kotlin ，不香吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "javakam/FileOperator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 晚上7:52
收件人:&nbsp;"javakam/FileOperator"<FileOperator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[javakam/FileOperator] 能给份java版的吗 (#1)

**Comment by DyncKathline** [comment]
> 建议直接上 Kotlin ，不香吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "javakam/FileOperator" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月5日(星期三) 晚上7:52 收件人:&nbsp;"javakam/FileOperator"<FileOperator@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[javakam/FileOperator] 能给份java版的吗 (#1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不想混编，之前的项目是Java的，主要是想兼容Android10的文件问题

**Comment by javakam** [comment]
新加入了 Java 版本的使用案例&nbsp; 👉&nbsp;&nbsp;sample_java


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "javakam/FileOperator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月6日(星期四) 下午4:10
收件人:&nbsp;"javakam/FileOperator"<FileOperator@noreply.github.com&gt;;
抄送:&nbsp;"风之旅人"<1772664927@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [javakam/FileOperator] 能给份java版的吗 (#1)





  
建议直接上 Kotlin ，不香吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "javakam/FileOperator" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月5日(星期三) 晚上7:52 收件人:&nbsp;"javakam/FileOperator"<FileOperator@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[javakam/FileOperator] 能给份java版的吗 (#1) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
不想混编，之前的项目是Java的，主要是想兼容Android10的文件问题

**Comment by Traveler1991** [comment]
找不到你给的这个路径咯【 https://github.com/javakam/FileOperator/tree/master/sample_java】

**Comment by javakam** [comment]
> 找不到你给的这个路径咯【 [https://github.com/javakam/FileOperator/tree/master/sample_java】](https://github.com/javakam/FileOperator/tree/master/sample_java%E3%80%91)

目前还真没有java版本的。。。你看看哪块儿代码有用可以参照着改成java语法就行，没有用到特别晦涩的Kotlin的东西
