### ISSUE TITLE
自定义FileType，选择文件提示“文件类型不匹配”

### ISSUE THREAD

**Issue by SSSSunrise** [javakam/FileOperator#45]
![image](https://user-images.githubusercontent.com/31717774/131099159-299251f6-d5b8-4e58-93b8-8454f83478a7.png)
![image](https://user-images.githubusercontent.com/31717774/131099224-d5dfc427-ff5a-47f0-899f-23cfdf915e2b.png)

**Comment by SSSSunrise** [comment]
刚才测试了一遍，没问题了；
但是文件浏览器会单独多出一个音频选项，这个怎么处理。

**Comment by javakam** [comment]
那个是系统的改不了，可以试试自定义文件管理器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 上午9:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [javakam/FileOperator] 自定义FileType，选择文件提示“文件类型不匹配” (#45)




 
刚才测试了一遍，没问题了；
 但是文件浏览器会单独多出一个音频选项，这个怎么处理。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SSSSunrise** [comment]
> 那个是系统的改不了，可以试试自定义文件管理器
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月30日(周一) 上午9:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [javakam/FileOperator] 自定义FileType，选择文件提示“文件类型不匹配” (#45) 刚才测试了一遍，没问题了； 但是文件浏览器会单独多出一个音频选项，这个怎么处理。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好的，基本可以满足使用了，产品如果后期要求再说😘
